//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonal
    {
        public System.Guid Personal_Id { get; set; }
        public string Personal_Identification { get; set; }
        public string Personal_FirstName { get; set; }
        public string Personal_LastName { get; set; }
        public string Personal_Phone { get; set; }
    }
}
